BEGIN;

ALTER TABLE "Team" FORCE ROW LEVEL SECURITY;
ALTER TABLE "User" FORCE ROW LEVEL SECURITY;
ALTER TABLE "MailboxConnection" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PhoneNumber" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Lead" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ConversationEvent" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Attachment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DerivedLeadProfile" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Task" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" FORCE ROW LEVEL SECURITY;

ALTER FUNCTION team_event_metadata(UUID) SET search_path = pg_catalog, public;

COMMIT;
